# routes.yaml
# All project routes are defined here

# index page route
routeSmsIndex:
  path:       /
  controller: Sms::index
  methods:    GET

# install page route
routeSmsInstall:
  path:       /sms/install
  controller: Sms::install
  methods:    GET

# uninstall page route
routeSmsUninstall:
  path:       /sms/uninstall
  controller: Sms::uninstall
  methods:    GET

# the only API endpoint route
routeSmsSend:
  path:       /sms/send
  controller: Sms::send
  methods:    GET

# report page route
routeSmsReport:
  path:       /sms/report
  controller: Sms::report
  methods:    GET

# report page search route
routeSmsSearch:
  path:       /sms/report/{phone}
  controller: Sms::search
  methods:    GET
